remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: [No Hi !! No Hello !!]
tagline: [ Please don't say just Hi or Hello in chat.. ]
description: [ Please don't say: just Hi or Hello in chats..  ]

github:
  owner_url: https://github.com/smitesh-sutaria
