remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: [No Hi !! No Hello !!]
tagline: [Please do not say just Hi or Hello in chats]
description: [Please do not say: just Hi or Hello in official chats]

github:
  owner_url: https://github.com/smitesh-sutaria
