remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

title: [No Hi !! No Hello !!]
tagline: [ Please don't say just Hi or Hello in chat.. ]
description: [ This is a page which can be put as status on your profile, to make sure just hi or hello is not entertained  ]
